version: "3.9"

networks: 
  pouletmayo: 

services:
  backend:
    build: ./backend
    deploy:
      replicas: 1
    environment: 
      - PouletMayo_Db__Host=db
      - PouletMayo_Db__User=root
      - PouletMayo_Db__Password=${MYSQL_ROOT_PASSWORD}
      - PouletMayo_Db__Database=pouletmayo
    ports:
      - 8000:8000
    networks: 
      - pouletmayo

  frontend:
    build: ./frontend
    deploy:
      replicas: 1
    ports:
      - 9000:9000
    networks: 
      - pouletmayo

