version: "3.9"

networks: 
  pouletmayo: 

services:
  backend:
    build: ./backend
    deploy:
      replicas: 1
    environment: 
      - PouletMayo_Db__Host=mysql
      - PouletMayo_Db__User=root
      - PouletMayo_Db__Password=${MYSQL_PWD}
      - PouletMayo_Db__Database=pouletmayo
    ports:
      - 8000:8000
    networks: 
      - pouletmayo
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1

  frontend:
    build: ./frontend
    deploy:
      replicas: 1
    ports:
      - 9000:9000
    networks: 
      - pouletmayo
    healthcheck:
      test: curl --fail http://localhost:9000 || exit 1

  wait-for-healthy:
    image: busybox
    depends_on: 
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

