on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  test: 
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}

    env:
      PouletMayo_Db__Host: localhost
      PouletMayo_Db__User: root
      PouletMayo_Db__Password: ${{ secrets.CI_DB_PASSWORD }}
      PouletMayo_Db__Database: pouletmayo

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore
    - name: Build
      run: | 
        dotnet run & 
        sleep 10 
        [[ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000/api/entreesdujour) == "200" ]] 

  build: 
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spm-backend:${{ env.BRANCH_NAME }}