name: Continuous integration

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  
jobs:
  frontend-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 17
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: Install dependencies
      run: npm install

    - name: Launch test 
      run: npm test
  
  backend-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      PouletMayo_Db__Host: localhost
      PouletMayo_Db__User: root
      PouletMayo_Db__Password: ${{ secrets.CI_DB_PASSWORD }}
      PouletMayo_Db__Database: pouletmayo

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore

  integration-test: 
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_PWD: ${{ secrets.CI_DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    steps:
    - uses: actions/checkout@v3

    - name: Run database migration
      run: ./bootstrap-mysql.sh
      working-directory: mysql

    - name: Compute env variable
      run: |
        echo "DOCKER_NETWORK=${{ job.services.mysql.network }}" >> $GITHUB_ENV

    - name: Start components
      run: docker compose -f docker-compose.build.yml up -d 

    - name: Run  k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: k6/script.js

    - name: Stop components
      run: docker compose -f docker-compose.build.yml down 


  build-image:
    strategy:
      matrix:
        component: ["frontend", "backend"]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [integration-test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Prepare job
      run: |
        echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ${{ matrix.component }}
        file: ${{ matrix.component }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/spm-${{ matrix.component }}:${{ github.ref_name }}
