on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  test: 
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js 17
      uses: actions/setup-node@v3
      with:
        node-version: 17
    - name: Install dependencies
      run: npm install
    - name: Launch test 
      run: npm test
    - name: Check frontend is respondig  
      run: | 
        npm start & 
        sleep 2 
        [[ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000) == "200" ]] 

  build-image: 
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spm-frontend:${{ env.BRANCH_NAME }}
